config/routes.rb
Splurty::Application.routes.draw do

   root 'static_pages#index'
   resources :quotes
   get 'about' => 'static_pages#about'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quote = Quote.order("RANDOM()").last
	end

	def new
		@quote = Quote.new
	end	

	def create
		Quote.create(quote_params)
		redirect_to quotes_path
	end

	private

	def quote_params
		params.require(:quote).permit(:saying, :author, :rating)
	end	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end	



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Splurty</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/index.html.erb
<div class="awesome-box">
	<h1>The best life tips..</h1>
	<h2>
		"
		<%= @quote.saying %>
		"
	</h2>
	<p>
		<%= @quote.author %>
	</p>

	<h3>
		Rating: 
		<% if @quote.rating %>
			<%= @quote.rating %>
		<% else %>
			<i>None</i>
		<% end %>
	</h3>	
		<br>
		<%= link_to 'Home', root_path, :class => 'btn btn-primary' %>
		<br>

</div>

app/views/quotes/new.html.erb
<div class="awesome-box">

<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

</div>

app/views/static_pages/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

	<div class="awesome-box col-xs-6 col-xs-offset-3 text-center">
		<h1> 
		Advice is Awesome!!!
		</h1>

		<br>
		<%= link_to 'Launch', quotes_path, :class => 'btn btn-primary' %>
		<br>
		<br>
		<%= link_to 'New quote', new_quote_path, :class => 'btn btn-primary' %>
		<br>
		<br>
</div>	
	